name: Build Example Model Pickles

on:
  workflow_dispatch:
  push:
    # paths:
    #   - example_model.ipynb
    #   - hello_numerai.ipynb
    #   - feature_neutralization.ipynb
    #   - target_ensemble.ipynb
    #   - signals/example_model.ipynb
    #   - crypto/example_model.ipynb
    branches:
      - master

concurrency: build-example-models

jobs:

  build_and_test:
    name: "Build Example Model Pickles"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install jupyter
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install -r https://raw.githubusercontent.com/numerai/numerai-predict/refs/heads/master/py3.12/requirements.txt
      - name: build-example-model
        run: |
          jupyter nbconvert \
            --execute numerai/example_model.ipynb \
            --ExecutePreprocessor.timeout=-1 \
            --to html
      - name: build-hello-numerai
        run: |
          jupyter nbconvert \
            --execute numerai/hello_numerai.ipynb \
            --ExecutePreprocessor.timeout=-1 \
            --to html
      - name: build-feature-neutralization
        run: |
          jupyter nbconvert \
            --execute numerai/feature_neutralization.ipynb \
            --ExecutePreprocessor.timeout=-1 \
            --to html
      - name: build-target-ensemble
        run: |
          jupyter nbconvert \
            --execute numerai/target_ensemble.ipynb \
            --ExecutePreprocessor.timeout=-1 \
            --to html
      - name: build-signals-example-model
        run: |
          jupyter nbconvert \
            --execute signals/example_model.ipynb \
            --ExecutePreprocessor.timeout=-1 \
            --to html
      - name: build-crypto-example-model
        run: |
          jupyter nbconvert \
            --execute crypto/example_model.ipynb \
            --ExecutePreprocessor.timeout=-1 \
            --to html
      - name: delete-html
        run: |
          rm numerai/example_model.html
          rm numerai/hello_numerai.html
          rm numerai/feature_neutralization.html
          rm numerai/target_ensemble.html
          rm signals/example_model.html
          rm crypto/example_model.html
      - name: move-pickles-to-cached-pickles-dir
        run: |
          mkdir -p cached-pickles/
          mv -f numerai/example_model.pkl cached-pickles/
          mv -f numerai/hello_numerai.pkl cached-pickles/
          mv -f numerai/feature_neutralization.pkl cached-pickles/
          mv -f numerai/target_ensemble.pkl cached-pickles/
          mv -f signals/example_model.pkl cached-pickles/signals_example_model.pkl
          mv -f crypto/example_model.pkl cached-pickles/crypto_example_model.pkl
      - name: commit-to-master
        uses: EndBug/add-and-commit@v9
        with:
          add: "cached-pickles/*"
